language: python

python:
    - 3.6
    - 3.5
    - 3.4
    - 3.3

install:
    - pip install -r requirements.txt

script:
    - coverage run --source=points -m unittest discover tests

after_success:
  - coveralls
